### ISSUE TITLE
Allow Opensearch as backend instead of Elasticsearch

### ISSUE THREAD

**Issue by jansyren** [arkime/arkime#1854] opened 2022-03-30 14:30 UTC
Verify future versions of Opensearch as this is becoming a very viable option as an Elastic replacement and it is fully open source as opposite from Elastic that has started to limit the usage. Right now version 7 and Opensearch 1.x are quite compatible but who knows if things will diverge in the future.

We have several Opensearch clusters available to use for indexing but installing and maintaining Elasticsearch and purchase licenses just for Arkime usage might not be a viable option, and I think others might have the same issue. Especially if you require things like AD logins and such.

**Comment by awick** [comment] 2022-03-30 15:18
Opensearch is already supported, are you having an issue?

**Comment by jansyren** [comment] 2022-03-30 20:43
Version 1.xx is since it is Elastic v7 compatible I am assuming, but reading the manual I see no direct mention of Opensearch and since Opensearch is forked from Elasticsearch 7.10 I fear that the two might diverge along the line. Or is it simply because you haven't just written it into the manual yet? 

I am simply concerned going forward with installation and then not be able to upgrade further down the line so to say.

**Comment by awick** [comment] 2022-03-30 21:54
Ok, but the title of the issue is "Allow Opensearch as backend instead of Elasticsearch", which we already do.

Yes they will diverge someday. We hope to continue to support both. Just like we hope to never require any pay Elasticsearch features.

If you really just want to see the text for Elasticsearch updated in the docs we would gladly accept pull requests. Although I'm not sure how to phrase "Elasticsearch/Opensearch/Opendistro compatible ..." which is one reason for now we've just left it.

Closing this issue for now, feel free to add a comment if I'm missing something or even better come on over to slack and discuss.

**Closed by awick** 2022-03-30 21:54 UTC

**Comment by mosajjal** [comment] 2022-10-17 19:53
hey @awick, is the list of Elastic APIs used by Arkime documented somewhere? I was thinking maybe someone could come up with a shim to plug other DBs to it just by simulating ES APIs
